name: Build and Push mailcatcher
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true    
  push:
    branches: [ main ]

jobs:
  build:
    name: mailcatcher-build
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io/sshaaf
          username: sshaaf
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: mailcatcher/Dockerfile
          push: true
          tags: quay.io/sshaaf/mailcatcher:${{ github.sha }}, quay.io/sshaaf/mailcatcher:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}